
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ItensPedido` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ItensPedido
 * 
 */
export type ItensPedidoModel = runtime.Types.Result.DefaultSelection<Prisma.$ItensPedidoPayload>

export type AggregateItensPedido = {
  _count: ItensPedidoCountAggregateOutputType | null
  _avg: ItensPedidoAvgAggregateOutputType | null
  _sum: ItensPedidoSumAggregateOutputType | null
  _min: ItensPedidoMinAggregateOutputType | null
  _max: ItensPedidoMaxAggregateOutputType | null
}

export type ItensPedidoAvgAggregateOutputType = {
  id: number | null
  pedidoId: number | null
  produtoId: number | null
  quantidade: number | null
  precoUnit: runtime.Decimal | null
}

export type ItensPedidoSumAggregateOutputType = {
  id: number | null
  pedidoId: number | null
  produtoId: number | null
  quantidade: number | null
  precoUnit: runtime.Decimal | null
}

export type ItensPedidoMinAggregateOutputType = {
  id: number | null
  pedidoId: number | null
  produtoId: number | null
  quantidade: number | null
  precoUnit: runtime.Decimal | null
}

export type ItensPedidoMaxAggregateOutputType = {
  id: number | null
  pedidoId: number | null
  produtoId: number | null
  quantidade: number | null
  precoUnit: runtime.Decimal | null
}

export type ItensPedidoCountAggregateOutputType = {
  id: number
  pedidoId: number
  produtoId: number
  quantidade: number
  precoUnit: number
  _all: number
}


export type ItensPedidoAvgAggregateInputType = {
  id?: true
  pedidoId?: true
  produtoId?: true
  quantidade?: true
  precoUnit?: true
}

export type ItensPedidoSumAggregateInputType = {
  id?: true
  pedidoId?: true
  produtoId?: true
  quantidade?: true
  precoUnit?: true
}

export type ItensPedidoMinAggregateInputType = {
  id?: true
  pedidoId?: true
  produtoId?: true
  quantidade?: true
  precoUnit?: true
}

export type ItensPedidoMaxAggregateInputType = {
  id?: true
  pedidoId?: true
  produtoId?: true
  quantidade?: true
  precoUnit?: true
}

export type ItensPedidoCountAggregateInputType = {
  id?: true
  pedidoId?: true
  produtoId?: true
  quantidade?: true
  precoUnit?: true
  _all?: true
}

export type ItensPedidoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ItensPedido to aggregate.
   */
  where?: Prisma.ItensPedidoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItensPedidos to fetch.
   */
  orderBy?: Prisma.ItensPedidoOrderByWithRelationInput | Prisma.ItensPedidoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ItensPedidoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItensPedidos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItensPedidos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ItensPedidos
  **/
  _count?: true | ItensPedidoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ItensPedidoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ItensPedidoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ItensPedidoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ItensPedidoMaxAggregateInputType
}

export type GetItensPedidoAggregateType<T extends ItensPedidoAggregateArgs> = {
      [P in keyof T & keyof AggregateItensPedido]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateItensPedido[P]>
    : Prisma.GetScalarType<T[P], AggregateItensPedido[P]>
}




export type ItensPedidoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ItensPedidoWhereInput
  orderBy?: Prisma.ItensPedidoOrderByWithAggregationInput | Prisma.ItensPedidoOrderByWithAggregationInput[]
  by: Prisma.ItensPedidoScalarFieldEnum[] | Prisma.ItensPedidoScalarFieldEnum
  having?: Prisma.ItensPedidoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ItensPedidoCountAggregateInputType | true
  _avg?: ItensPedidoAvgAggregateInputType
  _sum?: ItensPedidoSumAggregateInputType
  _min?: ItensPedidoMinAggregateInputType
  _max?: ItensPedidoMaxAggregateInputType
}

export type ItensPedidoGroupByOutputType = {
  id: number
  pedidoId: number
  produtoId: number
  quantidade: number
  precoUnit: runtime.Decimal
  _count: ItensPedidoCountAggregateOutputType | null
  _avg: ItensPedidoAvgAggregateOutputType | null
  _sum: ItensPedidoSumAggregateOutputType | null
  _min: ItensPedidoMinAggregateOutputType | null
  _max: ItensPedidoMaxAggregateOutputType | null
}

type GetItensPedidoGroupByPayload<T extends ItensPedidoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ItensPedidoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ItensPedidoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ItensPedidoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ItensPedidoGroupByOutputType[P]>
      }
    >
  >



export type ItensPedidoWhereInput = {
  AND?: Prisma.ItensPedidoWhereInput | Prisma.ItensPedidoWhereInput[]
  OR?: Prisma.ItensPedidoWhereInput[]
  NOT?: Prisma.ItensPedidoWhereInput | Prisma.ItensPedidoWhereInput[]
  id?: Prisma.IntFilter<"ItensPedido"> | number
  pedidoId?: Prisma.IntFilter<"ItensPedido"> | number
  produtoId?: Prisma.IntFilter<"ItensPedido"> | number
  quantidade?: Prisma.IntFilter<"ItensPedido"> | number
  precoUnit?: Prisma.DecimalFilter<"ItensPedido"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  pedido?: Prisma.XOR<Prisma.PedidoScalarRelationFilter, Prisma.PedidoWhereInput>
  produto?: Prisma.XOR<Prisma.ProdutoScalarRelationFilter, Prisma.ProdutoWhereInput>
}

export type ItensPedidoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  pedidoId?: Prisma.SortOrder
  produtoId?: Prisma.SortOrder
  quantidade?: Prisma.SortOrder
  precoUnit?: Prisma.SortOrder
  pedido?: Prisma.PedidoOrderByWithRelationInput
  produto?: Prisma.ProdutoOrderByWithRelationInput
}

export type ItensPedidoWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ItensPedidoWhereInput | Prisma.ItensPedidoWhereInput[]
  OR?: Prisma.ItensPedidoWhereInput[]
  NOT?: Prisma.ItensPedidoWhereInput | Prisma.ItensPedidoWhereInput[]
  pedidoId?: Prisma.IntFilter<"ItensPedido"> | number
  produtoId?: Prisma.IntFilter<"ItensPedido"> | number
  quantidade?: Prisma.IntFilter<"ItensPedido"> | number
  precoUnit?: Prisma.DecimalFilter<"ItensPedido"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  pedido?: Prisma.XOR<Prisma.PedidoScalarRelationFilter, Prisma.PedidoWhereInput>
  produto?: Prisma.XOR<Prisma.ProdutoScalarRelationFilter, Prisma.ProdutoWhereInput>
}, "id">

export type ItensPedidoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  pedidoId?: Prisma.SortOrder
  produtoId?: Prisma.SortOrder
  quantidade?: Prisma.SortOrder
  precoUnit?: Prisma.SortOrder
  _count?: Prisma.ItensPedidoCountOrderByAggregateInput
  _avg?: Prisma.ItensPedidoAvgOrderByAggregateInput
  _max?: Prisma.ItensPedidoMaxOrderByAggregateInput
  _min?: Prisma.ItensPedidoMinOrderByAggregateInput
  _sum?: Prisma.ItensPedidoSumOrderByAggregateInput
}

export type ItensPedidoScalarWhereWithAggregatesInput = {
  AND?: Prisma.ItensPedidoScalarWhereWithAggregatesInput | Prisma.ItensPedidoScalarWhereWithAggregatesInput[]
  OR?: Prisma.ItensPedidoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ItensPedidoScalarWhereWithAggregatesInput | Prisma.ItensPedidoScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ItensPedido"> | number
  pedidoId?: Prisma.IntWithAggregatesFilter<"ItensPedido"> | number
  produtoId?: Prisma.IntWithAggregatesFilter<"ItensPedido"> | number
  quantidade?: Prisma.IntWithAggregatesFilter<"ItensPedido"> | number
  precoUnit?: Prisma.DecimalWithAggregatesFilter<"ItensPedido"> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ItensPedidoCreateInput = {
  quantidade: number
  precoUnit: runtime.Decimal | runtime.DecimalJsLike | number | string
  pedido: Prisma.PedidoCreateNestedOneWithoutItensInput
  produto: Prisma.ProdutoCreateNestedOneWithoutItensPedidoInput
}

export type ItensPedidoUncheckedCreateInput = {
  id?: number
  pedidoId: number
  produtoId: number
  quantidade: number
  precoUnit: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ItensPedidoUpdateInput = {
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  pedido?: Prisma.PedidoUpdateOneRequiredWithoutItensNestedInput
  produto?: Prisma.ProdutoUpdateOneRequiredWithoutItensPedidoNestedInput
}

export type ItensPedidoUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  pedidoId?: Prisma.IntFieldUpdateOperationsInput | number
  produtoId?: Prisma.IntFieldUpdateOperationsInput | number
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ItensPedidoCreateManyInput = {
  id?: number
  pedidoId: number
  produtoId: number
  quantidade: number
  precoUnit: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ItensPedidoUpdateManyMutationInput = {
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ItensPedidoUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  pedidoId?: Prisma.IntFieldUpdateOperationsInput | number
  produtoId?: Prisma.IntFieldUpdateOperationsInput | number
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ItensPedidoListRelationFilter = {
  every?: Prisma.ItensPedidoWhereInput
  some?: Prisma.ItensPedidoWhereInput
  none?: Prisma.ItensPedidoWhereInput
}

export type ItensPedidoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ItensPedidoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pedidoId?: Prisma.SortOrder
  produtoId?: Prisma.SortOrder
  quantidade?: Prisma.SortOrder
  precoUnit?: Prisma.SortOrder
}

export type ItensPedidoAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pedidoId?: Prisma.SortOrder
  produtoId?: Prisma.SortOrder
  quantidade?: Prisma.SortOrder
  precoUnit?: Prisma.SortOrder
}

export type ItensPedidoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pedidoId?: Prisma.SortOrder
  produtoId?: Prisma.SortOrder
  quantidade?: Prisma.SortOrder
  precoUnit?: Prisma.SortOrder
}

export type ItensPedidoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pedidoId?: Prisma.SortOrder
  produtoId?: Prisma.SortOrder
  quantidade?: Prisma.SortOrder
  precoUnit?: Prisma.SortOrder
}

export type ItensPedidoSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pedidoId?: Prisma.SortOrder
  produtoId?: Prisma.SortOrder
  quantidade?: Prisma.SortOrder
  precoUnit?: Prisma.SortOrder
}

export type ItensPedidoCreateNestedManyWithoutProdutoInput = {
  create?: Prisma.XOR<Prisma.ItensPedidoCreateWithoutProdutoInput, Prisma.ItensPedidoUncheckedCreateWithoutProdutoInput> | Prisma.ItensPedidoCreateWithoutProdutoInput[] | Prisma.ItensPedidoUncheckedCreateWithoutProdutoInput[]
  connectOrCreate?: Prisma.ItensPedidoCreateOrConnectWithoutProdutoInput | Prisma.ItensPedidoCreateOrConnectWithoutProdutoInput[]
  createMany?: Prisma.ItensPedidoCreateManyProdutoInputEnvelope
  connect?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
}

export type ItensPedidoUncheckedCreateNestedManyWithoutProdutoInput = {
  create?: Prisma.XOR<Prisma.ItensPedidoCreateWithoutProdutoInput, Prisma.ItensPedidoUncheckedCreateWithoutProdutoInput> | Prisma.ItensPedidoCreateWithoutProdutoInput[] | Prisma.ItensPedidoUncheckedCreateWithoutProdutoInput[]
  connectOrCreate?: Prisma.ItensPedidoCreateOrConnectWithoutProdutoInput | Prisma.ItensPedidoCreateOrConnectWithoutProdutoInput[]
  createMany?: Prisma.ItensPedidoCreateManyProdutoInputEnvelope
  connect?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
}

export type ItensPedidoUpdateManyWithoutProdutoNestedInput = {
  create?: Prisma.XOR<Prisma.ItensPedidoCreateWithoutProdutoInput, Prisma.ItensPedidoUncheckedCreateWithoutProdutoInput> | Prisma.ItensPedidoCreateWithoutProdutoInput[] | Prisma.ItensPedidoUncheckedCreateWithoutProdutoInput[]
  connectOrCreate?: Prisma.ItensPedidoCreateOrConnectWithoutProdutoInput | Prisma.ItensPedidoCreateOrConnectWithoutProdutoInput[]
  upsert?: Prisma.ItensPedidoUpsertWithWhereUniqueWithoutProdutoInput | Prisma.ItensPedidoUpsertWithWhereUniqueWithoutProdutoInput[]
  createMany?: Prisma.ItensPedidoCreateManyProdutoInputEnvelope
  set?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  disconnect?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  delete?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  connect?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  update?: Prisma.ItensPedidoUpdateWithWhereUniqueWithoutProdutoInput | Prisma.ItensPedidoUpdateWithWhereUniqueWithoutProdutoInput[]
  updateMany?: Prisma.ItensPedidoUpdateManyWithWhereWithoutProdutoInput | Prisma.ItensPedidoUpdateManyWithWhereWithoutProdutoInput[]
  deleteMany?: Prisma.ItensPedidoScalarWhereInput | Prisma.ItensPedidoScalarWhereInput[]
}

export type ItensPedidoUncheckedUpdateManyWithoutProdutoNestedInput = {
  create?: Prisma.XOR<Prisma.ItensPedidoCreateWithoutProdutoInput, Prisma.ItensPedidoUncheckedCreateWithoutProdutoInput> | Prisma.ItensPedidoCreateWithoutProdutoInput[] | Prisma.ItensPedidoUncheckedCreateWithoutProdutoInput[]
  connectOrCreate?: Prisma.ItensPedidoCreateOrConnectWithoutProdutoInput | Prisma.ItensPedidoCreateOrConnectWithoutProdutoInput[]
  upsert?: Prisma.ItensPedidoUpsertWithWhereUniqueWithoutProdutoInput | Prisma.ItensPedidoUpsertWithWhereUniqueWithoutProdutoInput[]
  createMany?: Prisma.ItensPedidoCreateManyProdutoInputEnvelope
  set?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  disconnect?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  delete?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  connect?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  update?: Prisma.ItensPedidoUpdateWithWhereUniqueWithoutProdutoInput | Prisma.ItensPedidoUpdateWithWhereUniqueWithoutProdutoInput[]
  updateMany?: Prisma.ItensPedidoUpdateManyWithWhereWithoutProdutoInput | Prisma.ItensPedidoUpdateManyWithWhereWithoutProdutoInput[]
  deleteMany?: Prisma.ItensPedidoScalarWhereInput | Prisma.ItensPedidoScalarWhereInput[]
}

export type ItensPedidoCreateNestedManyWithoutPedidoInput = {
  create?: Prisma.XOR<Prisma.ItensPedidoCreateWithoutPedidoInput, Prisma.ItensPedidoUncheckedCreateWithoutPedidoInput> | Prisma.ItensPedidoCreateWithoutPedidoInput[] | Prisma.ItensPedidoUncheckedCreateWithoutPedidoInput[]
  connectOrCreate?: Prisma.ItensPedidoCreateOrConnectWithoutPedidoInput | Prisma.ItensPedidoCreateOrConnectWithoutPedidoInput[]
  createMany?: Prisma.ItensPedidoCreateManyPedidoInputEnvelope
  connect?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
}

export type ItensPedidoUncheckedCreateNestedManyWithoutPedidoInput = {
  create?: Prisma.XOR<Prisma.ItensPedidoCreateWithoutPedidoInput, Prisma.ItensPedidoUncheckedCreateWithoutPedidoInput> | Prisma.ItensPedidoCreateWithoutPedidoInput[] | Prisma.ItensPedidoUncheckedCreateWithoutPedidoInput[]
  connectOrCreate?: Prisma.ItensPedidoCreateOrConnectWithoutPedidoInput | Prisma.ItensPedidoCreateOrConnectWithoutPedidoInput[]
  createMany?: Prisma.ItensPedidoCreateManyPedidoInputEnvelope
  connect?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
}

export type ItensPedidoUpdateManyWithoutPedidoNestedInput = {
  create?: Prisma.XOR<Prisma.ItensPedidoCreateWithoutPedidoInput, Prisma.ItensPedidoUncheckedCreateWithoutPedidoInput> | Prisma.ItensPedidoCreateWithoutPedidoInput[] | Prisma.ItensPedidoUncheckedCreateWithoutPedidoInput[]
  connectOrCreate?: Prisma.ItensPedidoCreateOrConnectWithoutPedidoInput | Prisma.ItensPedidoCreateOrConnectWithoutPedidoInput[]
  upsert?: Prisma.ItensPedidoUpsertWithWhereUniqueWithoutPedidoInput | Prisma.ItensPedidoUpsertWithWhereUniqueWithoutPedidoInput[]
  createMany?: Prisma.ItensPedidoCreateManyPedidoInputEnvelope
  set?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  disconnect?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  delete?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  connect?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  update?: Prisma.ItensPedidoUpdateWithWhereUniqueWithoutPedidoInput | Prisma.ItensPedidoUpdateWithWhereUniqueWithoutPedidoInput[]
  updateMany?: Prisma.ItensPedidoUpdateManyWithWhereWithoutPedidoInput | Prisma.ItensPedidoUpdateManyWithWhereWithoutPedidoInput[]
  deleteMany?: Prisma.ItensPedidoScalarWhereInput | Prisma.ItensPedidoScalarWhereInput[]
}

export type ItensPedidoUncheckedUpdateManyWithoutPedidoNestedInput = {
  create?: Prisma.XOR<Prisma.ItensPedidoCreateWithoutPedidoInput, Prisma.ItensPedidoUncheckedCreateWithoutPedidoInput> | Prisma.ItensPedidoCreateWithoutPedidoInput[] | Prisma.ItensPedidoUncheckedCreateWithoutPedidoInput[]
  connectOrCreate?: Prisma.ItensPedidoCreateOrConnectWithoutPedidoInput | Prisma.ItensPedidoCreateOrConnectWithoutPedidoInput[]
  upsert?: Prisma.ItensPedidoUpsertWithWhereUniqueWithoutPedidoInput | Prisma.ItensPedidoUpsertWithWhereUniqueWithoutPedidoInput[]
  createMany?: Prisma.ItensPedidoCreateManyPedidoInputEnvelope
  set?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  disconnect?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  delete?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  connect?: Prisma.ItensPedidoWhereUniqueInput | Prisma.ItensPedidoWhereUniqueInput[]
  update?: Prisma.ItensPedidoUpdateWithWhereUniqueWithoutPedidoInput | Prisma.ItensPedidoUpdateWithWhereUniqueWithoutPedidoInput[]
  updateMany?: Prisma.ItensPedidoUpdateManyWithWhereWithoutPedidoInput | Prisma.ItensPedidoUpdateManyWithWhereWithoutPedidoInput[]
  deleteMany?: Prisma.ItensPedidoScalarWhereInput | Prisma.ItensPedidoScalarWhereInput[]
}

export type ItensPedidoCreateWithoutProdutoInput = {
  quantidade: number
  precoUnit: runtime.Decimal | runtime.DecimalJsLike | number | string
  pedido: Prisma.PedidoCreateNestedOneWithoutItensInput
}

export type ItensPedidoUncheckedCreateWithoutProdutoInput = {
  id?: number
  pedidoId: number
  quantidade: number
  precoUnit: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ItensPedidoCreateOrConnectWithoutProdutoInput = {
  where: Prisma.ItensPedidoWhereUniqueInput
  create: Prisma.XOR<Prisma.ItensPedidoCreateWithoutProdutoInput, Prisma.ItensPedidoUncheckedCreateWithoutProdutoInput>
}

export type ItensPedidoCreateManyProdutoInputEnvelope = {
  data: Prisma.ItensPedidoCreateManyProdutoInput | Prisma.ItensPedidoCreateManyProdutoInput[]
  skipDuplicates?: boolean
}

export type ItensPedidoUpsertWithWhereUniqueWithoutProdutoInput = {
  where: Prisma.ItensPedidoWhereUniqueInput
  update: Prisma.XOR<Prisma.ItensPedidoUpdateWithoutProdutoInput, Prisma.ItensPedidoUncheckedUpdateWithoutProdutoInput>
  create: Prisma.XOR<Prisma.ItensPedidoCreateWithoutProdutoInput, Prisma.ItensPedidoUncheckedCreateWithoutProdutoInput>
}

export type ItensPedidoUpdateWithWhereUniqueWithoutProdutoInput = {
  where: Prisma.ItensPedidoWhereUniqueInput
  data: Prisma.XOR<Prisma.ItensPedidoUpdateWithoutProdutoInput, Prisma.ItensPedidoUncheckedUpdateWithoutProdutoInput>
}

export type ItensPedidoUpdateManyWithWhereWithoutProdutoInput = {
  where: Prisma.ItensPedidoScalarWhereInput
  data: Prisma.XOR<Prisma.ItensPedidoUpdateManyMutationInput, Prisma.ItensPedidoUncheckedUpdateManyWithoutProdutoInput>
}

export type ItensPedidoScalarWhereInput = {
  AND?: Prisma.ItensPedidoScalarWhereInput | Prisma.ItensPedidoScalarWhereInput[]
  OR?: Prisma.ItensPedidoScalarWhereInput[]
  NOT?: Prisma.ItensPedidoScalarWhereInput | Prisma.ItensPedidoScalarWhereInput[]
  id?: Prisma.IntFilter<"ItensPedido"> | number
  pedidoId?: Prisma.IntFilter<"ItensPedido"> | number
  produtoId?: Prisma.IntFilter<"ItensPedido"> | number
  quantidade?: Prisma.IntFilter<"ItensPedido"> | number
  precoUnit?: Prisma.DecimalFilter<"ItensPedido"> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ItensPedidoCreateWithoutPedidoInput = {
  quantidade: number
  precoUnit: runtime.Decimal | runtime.DecimalJsLike | number | string
  produto: Prisma.ProdutoCreateNestedOneWithoutItensPedidoInput
}

export type ItensPedidoUncheckedCreateWithoutPedidoInput = {
  id?: number
  produtoId: number
  quantidade: number
  precoUnit: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ItensPedidoCreateOrConnectWithoutPedidoInput = {
  where: Prisma.ItensPedidoWhereUniqueInput
  create: Prisma.XOR<Prisma.ItensPedidoCreateWithoutPedidoInput, Prisma.ItensPedidoUncheckedCreateWithoutPedidoInput>
}

export type ItensPedidoCreateManyPedidoInputEnvelope = {
  data: Prisma.ItensPedidoCreateManyPedidoInput | Prisma.ItensPedidoCreateManyPedidoInput[]
  skipDuplicates?: boolean
}

export type ItensPedidoUpsertWithWhereUniqueWithoutPedidoInput = {
  where: Prisma.ItensPedidoWhereUniqueInput
  update: Prisma.XOR<Prisma.ItensPedidoUpdateWithoutPedidoInput, Prisma.ItensPedidoUncheckedUpdateWithoutPedidoInput>
  create: Prisma.XOR<Prisma.ItensPedidoCreateWithoutPedidoInput, Prisma.ItensPedidoUncheckedCreateWithoutPedidoInput>
}

export type ItensPedidoUpdateWithWhereUniqueWithoutPedidoInput = {
  where: Prisma.ItensPedidoWhereUniqueInput
  data: Prisma.XOR<Prisma.ItensPedidoUpdateWithoutPedidoInput, Prisma.ItensPedidoUncheckedUpdateWithoutPedidoInput>
}

export type ItensPedidoUpdateManyWithWhereWithoutPedidoInput = {
  where: Prisma.ItensPedidoScalarWhereInput
  data: Prisma.XOR<Prisma.ItensPedidoUpdateManyMutationInput, Prisma.ItensPedidoUncheckedUpdateManyWithoutPedidoInput>
}

export type ItensPedidoCreateManyProdutoInput = {
  id?: number
  pedidoId: number
  quantidade: number
  precoUnit: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ItensPedidoUpdateWithoutProdutoInput = {
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  pedido?: Prisma.PedidoUpdateOneRequiredWithoutItensNestedInput
}

export type ItensPedidoUncheckedUpdateWithoutProdutoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  pedidoId?: Prisma.IntFieldUpdateOperationsInput | number
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ItensPedidoUncheckedUpdateManyWithoutProdutoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  pedidoId?: Prisma.IntFieldUpdateOperationsInput | number
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ItensPedidoCreateManyPedidoInput = {
  id?: number
  produtoId: number
  quantidade: number
  precoUnit: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ItensPedidoUpdateWithoutPedidoInput = {
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  produto?: Prisma.ProdutoUpdateOneRequiredWithoutItensPedidoNestedInput
}

export type ItensPedidoUncheckedUpdateWithoutPedidoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  produtoId?: Prisma.IntFieldUpdateOperationsInput | number
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ItensPedidoUncheckedUpdateManyWithoutPedidoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  produtoId?: Prisma.IntFieldUpdateOperationsInput | number
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}



export type ItensPedidoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pedidoId?: boolean
  produtoId?: boolean
  quantidade?: boolean
  precoUnit?: boolean
  pedido?: boolean | Prisma.PedidoDefaultArgs<ExtArgs>
  produto?: boolean | Prisma.ProdutoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["itensPedido"]>



export type ItensPedidoSelectScalar = {
  id?: boolean
  pedidoId?: boolean
  produtoId?: boolean
  quantidade?: boolean
  precoUnit?: boolean
}

export type ItensPedidoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "pedidoId" | "produtoId" | "quantidade" | "precoUnit", ExtArgs["result"]["itensPedido"]>
export type ItensPedidoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pedido?: boolean | Prisma.PedidoDefaultArgs<ExtArgs>
  produto?: boolean | Prisma.ProdutoDefaultArgs<ExtArgs>
}

export type $ItensPedidoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ItensPedido"
  objects: {
    pedido: Prisma.$PedidoPayload<ExtArgs>
    produto: Prisma.$ProdutoPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    pedidoId: number
    produtoId: number
    quantidade: number
    precoUnit: runtime.Decimal
  }, ExtArgs["result"]["itensPedido"]>
  composites: {}
}

export type ItensPedidoGetPayload<S extends boolean | null | undefined | ItensPedidoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ItensPedidoPayload, S>

export type ItensPedidoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ItensPedidoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ItensPedidoCountAggregateInputType | true
  }

export interface ItensPedidoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ItensPedido'], meta: { name: 'ItensPedido' } }
  /**
   * Find zero or one ItensPedido that matches the filter.
   * @param {ItensPedidoFindUniqueArgs} args - Arguments to find a ItensPedido
   * @example
   * // Get one ItensPedido
   * const itensPedido = await prisma.itensPedido.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ItensPedidoFindUniqueArgs>(args: Prisma.SelectSubset<T, ItensPedidoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ItensPedidoClient<runtime.Types.Result.GetResult<Prisma.$ItensPedidoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ItensPedido that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ItensPedidoFindUniqueOrThrowArgs} args - Arguments to find a ItensPedido
   * @example
   * // Get one ItensPedido
   * const itensPedido = await prisma.itensPedido.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ItensPedidoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ItensPedidoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ItensPedidoClient<runtime.Types.Result.GetResult<Prisma.$ItensPedidoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ItensPedido that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItensPedidoFindFirstArgs} args - Arguments to find a ItensPedido
   * @example
   * // Get one ItensPedido
   * const itensPedido = await prisma.itensPedido.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ItensPedidoFindFirstArgs>(args?: Prisma.SelectSubset<T, ItensPedidoFindFirstArgs<ExtArgs>>): Prisma.Prisma__ItensPedidoClient<runtime.Types.Result.GetResult<Prisma.$ItensPedidoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ItensPedido that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItensPedidoFindFirstOrThrowArgs} args - Arguments to find a ItensPedido
   * @example
   * // Get one ItensPedido
   * const itensPedido = await prisma.itensPedido.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ItensPedidoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ItensPedidoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ItensPedidoClient<runtime.Types.Result.GetResult<Prisma.$ItensPedidoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ItensPedidos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItensPedidoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ItensPedidos
   * const itensPedidos = await prisma.itensPedido.findMany()
   * 
   * // Get first 10 ItensPedidos
   * const itensPedidos = await prisma.itensPedido.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const itensPedidoWithIdOnly = await prisma.itensPedido.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ItensPedidoFindManyArgs>(args?: Prisma.SelectSubset<T, ItensPedidoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItensPedidoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ItensPedido.
   * @param {ItensPedidoCreateArgs} args - Arguments to create a ItensPedido.
   * @example
   * // Create one ItensPedido
   * const ItensPedido = await prisma.itensPedido.create({
   *   data: {
   *     // ... data to create a ItensPedido
   *   }
   * })
   * 
   */
  create<T extends ItensPedidoCreateArgs>(args: Prisma.SelectSubset<T, ItensPedidoCreateArgs<ExtArgs>>): Prisma.Prisma__ItensPedidoClient<runtime.Types.Result.GetResult<Prisma.$ItensPedidoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ItensPedidos.
   * @param {ItensPedidoCreateManyArgs} args - Arguments to create many ItensPedidos.
   * @example
   * // Create many ItensPedidos
   * const itensPedido = await prisma.itensPedido.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ItensPedidoCreateManyArgs>(args?: Prisma.SelectSubset<T, ItensPedidoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ItensPedido.
   * @param {ItensPedidoDeleteArgs} args - Arguments to delete one ItensPedido.
   * @example
   * // Delete one ItensPedido
   * const ItensPedido = await prisma.itensPedido.delete({
   *   where: {
   *     // ... filter to delete one ItensPedido
   *   }
   * })
   * 
   */
  delete<T extends ItensPedidoDeleteArgs>(args: Prisma.SelectSubset<T, ItensPedidoDeleteArgs<ExtArgs>>): Prisma.Prisma__ItensPedidoClient<runtime.Types.Result.GetResult<Prisma.$ItensPedidoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ItensPedido.
   * @param {ItensPedidoUpdateArgs} args - Arguments to update one ItensPedido.
   * @example
   * // Update one ItensPedido
   * const itensPedido = await prisma.itensPedido.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ItensPedidoUpdateArgs>(args: Prisma.SelectSubset<T, ItensPedidoUpdateArgs<ExtArgs>>): Prisma.Prisma__ItensPedidoClient<runtime.Types.Result.GetResult<Prisma.$ItensPedidoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ItensPedidos.
   * @param {ItensPedidoDeleteManyArgs} args - Arguments to filter ItensPedidos to delete.
   * @example
   * // Delete a few ItensPedidos
   * const { count } = await prisma.itensPedido.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ItensPedidoDeleteManyArgs>(args?: Prisma.SelectSubset<T, ItensPedidoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ItensPedidos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItensPedidoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ItensPedidos
   * const itensPedido = await prisma.itensPedido.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ItensPedidoUpdateManyArgs>(args: Prisma.SelectSubset<T, ItensPedidoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ItensPedido.
   * @param {ItensPedidoUpsertArgs} args - Arguments to update or create a ItensPedido.
   * @example
   * // Update or create a ItensPedido
   * const itensPedido = await prisma.itensPedido.upsert({
   *   create: {
   *     // ... data to create a ItensPedido
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ItensPedido we want to update
   *   }
   * })
   */
  upsert<T extends ItensPedidoUpsertArgs>(args: Prisma.SelectSubset<T, ItensPedidoUpsertArgs<ExtArgs>>): Prisma.Prisma__ItensPedidoClient<runtime.Types.Result.GetResult<Prisma.$ItensPedidoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ItensPedidos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItensPedidoCountArgs} args - Arguments to filter ItensPedidos to count.
   * @example
   * // Count the number of ItensPedidos
   * const count = await prisma.itensPedido.count({
   *   where: {
   *     // ... the filter for the ItensPedidos we want to count
   *   }
   * })
  **/
  count<T extends ItensPedidoCountArgs>(
    args?: Prisma.Subset<T, ItensPedidoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ItensPedidoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ItensPedido.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItensPedidoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ItensPedidoAggregateArgs>(args: Prisma.Subset<T, ItensPedidoAggregateArgs>): Prisma.PrismaPromise<GetItensPedidoAggregateType<T>>

  /**
   * Group by ItensPedido.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItensPedidoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ItensPedidoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ItensPedidoGroupByArgs['orderBy'] }
      : { orderBy?: ItensPedidoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ItensPedidoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetItensPedidoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ItensPedido model
 */
readonly fields: ItensPedidoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ItensPedido.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ItensPedidoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  pedido<T extends Prisma.PedidoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PedidoDefaultArgs<ExtArgs>>): Prisma.Prisma__PedidoClient<runtime.Types.Result.GetResult<Prisma.$PedidoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  produto<T extends Prisma.ProdutoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProdutoDefaultArgs<ExtArgs>>): Prisma.Prisma__ProdutoClient<runtime.Types.Result.GetResult<Prisma.$ProdutoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ItensPedido model
 */
export interface ItensPedidoFieldRefs {
  readonly id: Prisma.FieldRef<"ItensPedido", 'Int'>
  readonly pedidoId: Prisma.FieldRef<"ItensPedido", 'Int'>
  readonly produtoId: Prisma.FieldRef<"ItensPedido", 'Int'>
  readonly quantidade: Prisma.FieldRef<"ItensPedido", 'Int'>
  readonly precoUnit: Prisma.FieldRef<"ItensPedido", 'Decimal'>
}
    

// Custom InputTypes
/**
 * ItensPedido findUnique
 */
export type ItensPedidoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItensPedido
   */
  select?: Prisma.ItensPedidoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItensPedido
   */
  omit?: Prisma.ItensPedidoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItensPedidoInclude<ExtArgs> | null
  /**
   * Filter, which ItensPedido to fetch.
   */
  where: Prisma.ItensPedidoWhereUniqueInput
}

/**
 * ItensPedido findUniqueOrThrow
 */
export type ItensPedidoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItensPedido
   */
  select?: Prisma.ItensPedidoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItensPedido
   */
  omit?: Prisma.ItensPedidoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItensPedidoInclude<ExtArgs> | null
  /**
   * Filter, which ItensPedido to fetch.
   */
  where: Prisma.ItensPedidoWhereUniqueInput
}

/**
 * ItensPedido findFirst
 */
export type ItensPedidoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItensPedido
   */
  select?: Prisma.ItensPedidoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItensPedido
   */
  omit?: Prisma.ItensPedidoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItensPedidoInclude<ExtArgs> | null
  /**
   * Filter, which ItensPedido to fetch.
   */
  where?: Prisma.ItensPedidoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItensPedidos to fetch.
   */
  orderBy?: Prisma.ItensPedidoOrderByWithRelationInput | Prisma.ItensPedidoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ItensPedidos.
   */
  cursor?: Prisma.ItensPedidoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItensPedidos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItensPedidos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ItensPedidos.
   */
  distinct?: Prisma.ItensPedidoScalarFieldEnum | Prisma.ItensPedidoScalarFieldEnum[]
}

/**
 * ItensPedido findFirstOrThrow
 */
export type ItensPedidoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItensPedido
   */
  select?: Prisma.ItensPedidoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItensPedido
   */
  omit?: Prisma.ItensPedidoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItensPedidoInclude<ExtArgs> | null
  /**
   * Filter, which ItensPedido to fetch.
   */
  where?: Prisma.ItensPedidoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItensPedidos to fetch.
   */
  orderBy?: Prisma.ItensPedidoOrderByWithRelationInput | Prisma.ItensPedidoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ItensPedidos.
   */
  cursor?: Prisma.ItensPedidoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItensPedidos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItensPedidos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ItensPedidos.
   */
  distinct?: Prisma.ItensPedidoScalarFieldEnum | Prisma.ItensPedidoScalarFieldEnum[]
}

/**
 * ItensPedido findMany
 */
export type ItensPedidoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItensPedido
   */
  select?: Prisma.ItensPedidoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItensPedido
   */
  omit?: Prisma.ItensPedidoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItensPedidoInclude<ExtArgs> | null
  /**
   * Filter, which ItensPedidos to fetch.
   */
  where?: Prisma.ItensPedidoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItensPedidos to fetch.
   */
  orderBy?: Prisma.ItensPedidoOrderByWithRelationInput | Prisma.ItensPedidoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ItensPedidos.
   */
  cursor?: Prisma.ItensPedidoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItensPedidos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItensPedidos.
   */
  skip?: number
  distinct?: Prisma.ItensPedidoScalarFieldEnum | Prisma.ItensPedidoScalarFieldEnum[]
}

/**
 * ItensPedido create
 */
export type ItensPedidoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItensPedido
   */
  select?: Prisma.ItensPedidoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItensPedido
   */
  omit?: Prisma.ItensPedidoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItensPedidoInclude<ExtArgs> | null
  /**
   * The data needed to create a ItensPedido.
   */
  data: Prisma.XOR<Prisma.ItensPedidoCreateInput, Prisma.ItensPedidoUncheckedCreateInput>
}

/**
 * ItensPedido createMany
 */
export type ItensPedidoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ItensPedidos.
   */
  data: Prisma.ItensPedidoCreateManyInput | Prisma.ItensPedidoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ItensPedido update
 */
export type ItensPedidoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItensPedido
   */
  select?: Prisma.ItensPedidoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItensPedido
   */
  omit?: Prisma.ItensPedidoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItensPedidoInclude<ExtArgs> | null
  /**
   * The data needed to update a ItensPedido.
   */
  data: Prisma.XOR<Prisma.ItensPedidoUpdateInput, Prisma.ItensPedidoUncheckedUpdateInput>
  /**
   * Choose, which ItensPedido to update.
   */
  where: Prisma.ItensPedidoWhereUniqueInput
}

/**
 * ItensPedido updateMany
 */
export type ItensPedidoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ItensPedidos.
   */
  data: Prisma.XOR<Prisma.ItensPedidoUpdateManyMutationInput, Prisma.ItensPedidoUncheckedUpdateManyInput>
  /**
   * Filter which ItensPedidos to update
   */
  where?: Prisma.ItensPedidoWhereInput
  /**
   * Limit how many ItensPedidos to update.
   */
  limit?: number
}

/**
 * ItensPedido upsert
 */
export type ItensPedidoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItensPedido
   */
  select?: Prisma.ItensPedidoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItensPedido
   */
  omit?: Prisma.ItensPedidoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItensPedidoInclude<ExtArgs> | null
  /**
   * The filter to search for the ItensPedido to update in case it exists.
   */
  where: Prisma.ItensPedidoWhereUniqueInput
  /**
   * In case the ItensPedido found by the `where` argument doesn't exist, create a new ItensPedido with this data.
   */
  create: Prisma.XOR<Prisma.ItensPedidoCreateInput, Prisma.ItensPedidoUncheckedCreateInput>
  /**
   * In case the ItensPedido was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ItensPedidoUpdateInput, Prisma.ItensPedidoUncheckedUpdateInput>
}

/**
 * ItensPedido delete
 */
export type ItensPedidoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItensPedido
   */
  select?: Prisma.ItensPedidoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItensPedido
   */
  omit?: Prisma.ItensPedidoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItensPedidoInclude<ExtArgs> | null
  /**
   * Filter which ItensPedido to delete.
   */
  where: Prisma.ItensPedidoWhereUniqueInput
}

/**
 * ItensPedido deleteMany
 */
export type ItensPedidoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ItensPedidos to delete
   */
  where?: Prisma.ItensPedidoWhereInput
  /**
   * Limit how many ItensPedidos to delete.
   */
  limit?: number
}

/**
 * ItensPedido without action
 */
export type ItensPedidoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItensPedido
   */
  select?: Prisma.ItensPedidoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItensPedido
   */
  omit?: Prisma.ItensPedidoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItensPedidoInclude<ExtArgs> | null
}
